apiVersion: apps/v1
kind: Deployment
metadata:
  name: member
  labels:
    k8s-app: member
spec:
  selector:
    matchLabels:
      k8s-app: member
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: member
    spec:
      containers:
      - name: member
        image: registry-intl.cn-shanghai.aliyuncs.com/slither/agent:httpservertemp
        imagePullPolicy: Always         
        ports:
        - containerPort: 30003      
      - name: myredis
        image: redis
        imagePullPolicy: Always 
        ports:
        - containerPort: 6379  
---
apiVersion: v1
kind: Service
metadata:
  name: member
spec:
  type: NodePort
  selector:
    k8s-app: member
  ports:
  - protocol: TCP
    name: member
    port: 30003 
    targetPort: 30003 
    nodePort: 30003        
   
